export class RegisterUserDto {
    private constructor(
        public id: number,
        public auth: string,
        public confirmed: string,
        public policyagreed: string,
        public deleted: string,
        public suspended: string,
        public mnethostid: string,
        public username: string,
        public password: string,
        public idnumber: string,
        public firstname: string,
        public lastname: string,
        public email: string,
        public emailstop: string,
        public phone1: string,
        public phone2: string,
        public institution: string,
        public department: string,
        public address: string,
        public city: string,
        public country: string,
        public lang: string,
        public calendartype: string,
        public theme: string,
        public timezone: string,
        public firstaccess: string,
        public lastaccess: string,
        public lastlogin: string,
        public currentlogin: string,
        public lastip: string,
        public secret: string,
        public picture: string,
        public description: null,
        public descriptionformat: string,
        public mailformat: string,
        public maildigest: string,
        public maildisplay: string,
        public autosubscribe: string,
        public trackforums: string,
        public timecreated: string,
        public timemodified: string,
        public trustbitmask: string,
        public imagealt: null,
        public lastnamephonetic: null,
        public firstnamephonetic: null,
        public middlename: null,
        public alternatename: null,
        public moodlenetprofile: null
    ){}

    static create(object:{[key:string]:any}):[string?,RegisterUserDto?]{
        const {
            id,
            auth,
            confirmed,
            policyagreed,
            deleted,
            suspended,
            mnethostid,
            username,
            password,
            idnumber,
            firstname,
            lastname,
            email,
            emailstop,
            phone1,
            phone2,
            institution,
            department,
            address,
            city,
            country,
            lang,
            calendartype,
            theme,
            timezone,
            firstaccess,
            lastaccess,
            lastlogin,
            currentlogin,
            lastip,
            secret,
            picture,
            description,
            descriptionformat,
            mailformat,
            maildigest,
            maildisplay,
            autosubscribe,
            trackforums,
            timecreated,
            timemodified,
            trustbitmask,
            imagealt,
            lastnamephonetic,
            firstnamephonetic,
            middlename,
            alternatename,
            moodlenetprofile,
        } = object

        if(!id) return ['Missing external id']
        if(!username) return ['Missing username']
        if(!firstname) return ['Missing firstname']
        if(!lastname) return ['Missing lastname']
        if(!institution) return ['Missing institution']

        return[
            undefined,
            new RegisterUserDto(
                id,
                auth,
                confirmed,
                policyagreed,
                deleted,
                suspended,
                mnethostid,
                username,
                password,
                idnumber,
                firstname,
                lastname,
                email,
                emailstop,
                phone1,
                phone2,
                institution,
                department,
                address,
                city,
                country,
                lang,
                calendartype,
                theme,
                timezone,
                firstaccess,
                lastaccess,
                lastlogin,
                currentlogin,
                lastip,
                secret,
                picture,
                description,
                descriptionformat,
                mailformat,
                maildigest,
                maildisplay,
                autosubscribe,
                trackforums,
                timecreated,
                timemodified,
                trustbitmask,
                imagealt,
                lastnamephonetic,
                firstnamephonetic,
                middlename,
                alternatename,
                moodlenetprofile
            )
        ];
    }
}