export class UserMdlDto {
    private constructor(
        public id: number,
        public auth: string,
        public confirmed: string,
        public policyagreed: string,
        public deleted: string,
        public suspended: string,
        public mnethostid: string,
        public username: string,
        public password: string,
        public idnumber: string,
        public firstname: string,
        public lastname: string,
        public email: string,
        public emailstop: string,
        public phone1: string,
        public phone2: string,
        public institution: string,
        public department: string,
        public address: string,
        public city: string,
        public country: string,
        public lang: string,
        public calendartype: string,
        public theme: string,
        public timezone: string,
        public firstaccess: string,
        public lastaccess: string,
        public lastlogin: string,
        public currentlogin: string,
        public lastip: string,
        public secret: string,
        public picture: string,
        public description: null,
        public descriptionformat: string,
        public mailformat: string,
        public maildigest: string,
        public maildisplay: string,
        public autosubscribe: string,
        public trackforums: string,
        public timecreated: string,
        public timemodified: string,
        public trustbitmask: string,
        public imagealt: null,
        public lastnamephonetic: null,
        public firstnamephonetic: null,
        public middlename: null,
        public alternatename: null,
        public moodlenetprofile: null
    ){

    }
}