export class EnrolmentMdlDto {
    private constructor(
        public id: number,
        public status: boolean,
        public enrolid: number,
        public userid: number,
        public timestart: number,
        public timeend: number,
        public modifierid: number,
        public timecreated: number,
        public timemodified: number,
        public enrol: string,
        public courseid: number,
        public sortorder: number,
        public name: string | null,
        public enrolperiod: number,
        public enrolstartdate: number,
        public enrolenddate: number,
        public expirynotify: number,
        public expirythreshold: number,
        public notifyall: boolean,
        public password: string | null,
        public cost: string | null,
        public currency: string | null,
        public roleid: number,
        public customint1: string | null,
        public customint2: string | null,
        public customint3: string | null,
        public customint4: string | null,
        public customint5: string | null,
        public customint6: string | null,
        public customint7: string | null,
        public customint8: string | null,
        public customchar1: string | null,
        public customchar2: string | null,
        public customchar3: string | null,
        public customdec1: string | null,
        public customdec2: string | null,
        public customtext1: string | null,
        public customtext2: string | null,
        public customtext3: string | null,
        public customtext4: string | null
    ){}
}